/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Trabalho1;

import static java.lang.Double.parseDouble;
import static java.lang.Integer.parseInt;
import java.util.ArrayList;
import javax.swing.JTextField;

/**
 *
 * @author Nicolau&Beatriz
 */

public class CadastroContaComum extends javax.swing.JFrame {
    
    
    
    public CadastroContaComum() {
        initComponents();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCadastroComum = new javax.swing.JButton();
        jLabelTituloComum = new javax.swing.JLabel();
        jTextNomeComum = new javax.swing.JTextField();
        jTextNumeroComum = new javax.swing.JTextField();
        jTextSaldoComum = new javax.swing.JTextField();
        jLabelNomeComum = new javax.swing.JLabel();
        jLabelNumeroComum = new javax.swing.JLabel();
        jLabelSaldoInicialComum = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonCadastroComum.setText("CADASTRAR");
        jButtonCadastroComum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroComumActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastroComum);
        jButtonCadastroComum.setBounds(140, 180, 130, 30);

        jLabelTituloComum.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabelTituloComum.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloComum.setText("CONTA COMUM");
        getContentPane().add(jLabelTituloComum);
        jLabelTituloComum.setBounds(150, 40, 120, 14);

        jTextNomeComum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextNomeComumActionPerformed(evt);
            }
        });
        getContentPane().add(jTextNomeComum);
        jTextNomeComum.setBounds(120, 60, 200, 30);
        getContentPane().add(jTextNumeroComum);
        jTextNumeroComum.setBounds(120, 100, 200, 30);
        getContentPane().add(jTextSaldoComum);
        jTextSaldoComum.setBounds(120, 140, 200, 30);

        jLabelNomeComum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNomeComum.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomeComum.setText("NOME:");
        getContentPane().add(jLabelNomeComum);
        jLabelNomeComum.setBounds(70, 60, 80, 30);

        jLabelNumeroComum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNumeroComum.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumeroComum.setText("NÚMERO: ");
        getContentPane().add(jLabelNumeroComum);
        jLabelNumeroComum.setBounds(60, 100, 70, 30);

        jLabelSaldoInicialComum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelSaldoInicialComum.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSaldoInicialComum.setText("SALDO: ");
        getContentPane().add(jLabelSaldoInicialComum);
        jLabelSaldoInicialComum.setBounds(70, 140, 110, 30);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.jpg"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(0, 0, 412, 223);

        setSize(new java.awt.Dimension(429, 261));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButtonCadastroComumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroComumActionPerformed
         // objeto que envia dados para o metodo principal
        Principal enviarComum  = new Principal();
        // cria um objeto da tela 3
        CadastroContaPoupanca tela3 = new CadastroContaPoupanca();
        String nome = jTextNomeComum.getText();
        int numero = parseInt(jTextNumeroComum.getText());
        double saldo = parseDouble(jTextSaldoComum.getText());
        enviarComum.recebendoComum(nome,numero,saldo);
        
        // torna visible a tela 3   
         tela3.setVisible(true);
         
        // oculta a tela atual
        dispose();
    }//GEN-LAST:event_jButtonCadastroComumActionPerformed
     
      
    

    
    
    
    private void jTextNomeComumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextNomeComumActionPerformed
        
    }//GEN-LAST:event_jTextNomeComumActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroContaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroContaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroContaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroContaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    
    
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroContaComum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastroComum;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelNomeComum;
    private javax.swing.JLabel jLabelNumeroComum;
    private javax.swing.JLabel jLabelSaldoInicialComum;
    private javax.swing.JLabel jLabelTituloComum;
    private javax.swing.JTextField jTextNomeComum;
    private javax.swing.JTextField jTextNumeroComum;
    private javax.swing.JTextField jTextSaldoComum;
    // End of variables declaration//GEN-END:variables
}
