/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Trabalho1;

import static java.lang.Double.parseDouble;
import static java.lang.Integer.parseInt;

/**
 *
 * @author Nicolau&Beatriz
 */
public class CadastroContaPoupanca extends javax.swing.JFrame {

    /**
     * Creates new form CadastroContaComum
     */
    public CadastroContaPoupanca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextReajuste = new javax.swing.JTextField();
        jLabelReajuste = new javax.swing.JLabel();
        jButtonCadastroPoupanca = new javax.swing.JButton();
        jLabelTituloPoupanca = new javax.swing.JLabel();
        jTextNomePoupanca = new javax.swing.JTextField();
        jTextNumeroPoupanca = new javax.swing.JTextField();
        jTextSaldoPoupanca = new javax.swing.JTextField();
        jLabelNomePoupanca = new javax.swing.JLabel();
        jLabelNumeroPoupanca = new javax.swing.JLabel();
        jLabelSaldoInicialPoupanca = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);
        getContentPane().add(jTextReajuste);
        jTextReajuste.setBounds(120, 150, 200, 30);

        jLabelReajuste.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelReajuste.setForeground(new java.awt.Color(255, 255, 255));
        jLabelReajuste.setText("REAJUSTE(%):");
        getContentPane().add(jLabelReajuste);
        jLabelReajuste.setBounds(20, 150, 120, 30);

        jButtonCadastroPoupanca.setText("CADASTRAR");
        jButtonCadastroPoupanca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroPoupancaActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastroPoupanca);
        jButtonCadastroPoupanca.setBounds(150, 190, 130, 30);

        jLabelTituloPoupanca.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabelTituloPoupanca.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloPoupanca.setText("CONTA POUPANÇA");
        getContentPane().add(jLabelTituloPoupanca);
        jLabelTituloPoupanca.setBounds(150, 10, 140, 14);
        getContentPane().add(jTextNomePoupanca);
        jTextNomePoupanca.setBounds(120, 30, 200, 30);
        getContentPane().add(jTextNumeroPoupanca);
        jTextNumeroPoupanca.setBounds(120, 70, 200, 30);
        getContentPane().add(jTextSaldoPoupanca);
        jTextSaldoPoupanca.setBounds(120, 110, 200, 30);

        jLabelNomePoupanca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNomePoupanca.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomePoupanca.setText("NOME:");
        getContentPane().add(jLabelNomePoupanca);
        jLabelNomePoupanca.setBounds(70, 30, 80, 30);

        jLabelNumeroPoupanca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNumeroPoupanca.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumeroPoupanca.setText("NÚMERO: ");
        getContentPane().add(jLabelNumeroPoupanca);
        jLabelNumeroPoupanca.setBounds(60, 70, 70, 30);

        jLabelSaldoInicialPoupanca.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelSaldoInicialPoupanca.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSaldoInicialPoupanca.setText("SALDO: ");
        getContentPane().add(jLabelSaldoInicialPoupanca);
        jLabelSaldoInicialPoupanca.setBounds(70, 110, 110, 30);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.jpg"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(0, 0, 412, 223);

        setSize(new java.awt.Dimension(429, 261));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private void jButtonCadastroPoupancaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroPoupancaActionPerformed
            
            // objeto que envia dados para o metodo principal
            Principal enviarPoupanca  = new Principal();
            // cria um objeto da tela 4
            CadastroContaEspecial tela4 = new CadastroContaEspecial();
            
            String nome = jTextNomePoupanca.getText();
            int numero = parseInt(jTextNumeroPoupanca.getText());
            double saldo= parseDouble(jTextSaldoPoupanca.getText());            
            double taxa;  
            if (jTextReajuste.getText().length() == 0){                
                taxa = 0;
            }                
            else{                
                taxa = parseDouble(jTextReajuste.getText());
            }
            enviarPoupanca.recebendoPoupanca(nome,numero,saldo,taxa);
                            
            tela4.setVisible(true);
            dispose();
    }//GEN-LAST:event_jButtonCadastroPoupancaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroContaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroContaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroContaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroContaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroContaPoupanca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastroPoupanca;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelNomePoupanca;
    private javax.swing.JLabel jLabelNumeroPoupanca;
    private javax.swing.JLabel jLabelReajuste;
    private javax.swing.JLabel jLabelSaldoInicialPoupanca;
    private javax.swing.JLabel jLabelTituloPoupanca;
    private javax.swing.JTextField jTextNomePoupanca;
    private javax.swing.JTextField jTextNumeroPoupanca;
    private javax.swing.JTextField jTextReajuste;
    private javax.swing.JTextField jTextSaldoPoupanca;
    // End of variables declaration//GEN-END:variables
}
