/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Trabalho1;

import static java.lang.Double.parseDouble;
import static java.lang.Integer.parseInt;

/**
 *
 * @author Nicolau&Beatriz
 */
public class CadastroContaEspecial extends javax.swing.JFrame {

    /**
     * Creates new form CadastroContaComum
     */
    public CadastroContaEspecial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCadastroEspecial = new javax.swing.JButton();
        jTextMulta = new javax.swing.JTextField();
        jLabelTituloEspecial = new javax.swing.JLabel();
        jTextNomeEspecial = new javax.swing.JTextField();
        jTextLimite = new javax.swing.JTextField();
        jTextNumeroEspecial = new javax.swing.JTextField();
        jTextSaldoEspecial = new javax.swing.JTextField();
        jLabelMulta = new javax.swing.JLabel();
        jLabelNomeEspecial2 = new javax.swing.JLabel();
        jLabelNomeEspecial1 = new javax.swing.JLabel();
        jLabelNumeroEspecial = new javax.swing.JLabel();
        jLabelSaldoInicialEspecial = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonCadastroEspecial.setText("CADASTRAR");
        jButtonCadastroEspecial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastroEspecialActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastroEspecial);
        jButtonCadastroEspecial.setBounds(150, 180, 130, 30);
        getContentPane().add(jTextMulta);
        jTextMulta.setBounds(120, 140, 200, 30);

        jLabelTituloEspecial.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabelTituloEspecial.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloEspecial.setText("CONTA ESPECIAL");
        getContentPane().add(jLabelTituloEspecial);
        jLabelTituloEspecial.setBounds(160, 0, 120, 20);
        getContentPane().add(jTextNomeEspecial);
        jTextNomeEspecial.setBounds(120, 20, 200, 30);

        jTextLimite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLimiteActionPerformed(evt);
            }
        });
        getContentPane().add(jTextLimite);
        jTextLimite.setBounds(120, 110, 200, 30);
        getContentPane().add(jTextNumeroEspecial);
        jTextNumeroEspecial.setBounds(120, 50, 200, 30);
        getContentPane().add(jTextSaldoEspecial);
        jTextSaldoEspecial.setBounds(120, 80, 200, 30);

        jLabelMulta.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelMulta.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMulta.setText("MULTA:");
        getContentPane().add(jLabelMulta);
        jLabelMulta.setBounds(60, 140, 90, 30);

        jLabelNomeEspecial2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNomeEspecial2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomeEspecial2.setText("LIMITE:");
        getContentPane().add(jLabelNomeEspecial2);
        jLabelNomeEspecial2.setBounds(60, 110, 90, 30);

        jLabelNomeEspecial1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNomeEspecial1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNomeEspecial1.setText("NOME:");
        getContentPane().add(jLabelNomeEspecial1);
        jLabelNomeEspecial1.setBounds(70, 20, 90, 30);

        jLabelNumeroEspecial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNumeroEspecial.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumeroEspecial.setText("NÚMERO: ");
        getContentPane().add(jLabelNumeroEspecial);
        jLabelNumeroEspecial.setBounds(50, 50, 80, 30);

        jLabelSaldoInicialEspecial.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelSaldoInicialEspecial.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSaldoInicialEspecial.setText("SALDO: ");
        getContentPane().add(jLabelSaldoInicialEspecial);
        jLabelSaldoInicialEspecial.setBounds(60, 80, 120, 30);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.jpg"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(0, 0, 412, 223);

        setSize(new java.awt.Dimension(429, 261));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastroEspecialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastroEspecialActionPerformed
        // objeto que envia dados para o metodo principal    
        Principal enviarEspecial = new Principal();
        
        Operacoes tela5 = new Operacoes();
        String nome = jTextNomeEspecial.getText();
        int numero = parseInt(jTextNumeroEspecial.getText());
        double saldo = parseDouble(jTextSaldoEspecial.getText());            
        double multa = parseDouble(jTextMulta.getText());
        int limite = parseInt(jTextLimite.getText());        
        enviarEspecial.recebendoEspecial(nome,numero,saldo,limite,multa);
        tela5.setVisible(true);
        dispose();
        
    }//GEN-LAST:event_jButtonCadastroEspecialActionPerformed

    private void jTextLimiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLimiteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLimiteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroContaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroContaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroContaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroContaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroContaEspecial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastroEspecial;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelMulta;
    private javax.swing.JLabel jLabelNomeEspecial1;
    private javax.swing.JLabel jLabelNomeEspecial2;
    private javax.swing.JLabel jLabelNumeroEspecial;
    private javax.swing.JLabel jLabelSaldoInicialEspecial;
    private javax.swing.JLabel jLabelTituloEspecial;
    private javax.swing.JTextField jTextLimite;
    private javax.swing.JTextField jTextMulta;
    private javax.swing.JTextField jTextNomeEspecial;
    private javax.swing.JTextField jTextNumeroEspecial;
    private javax.swing.JTextField jTextSaldoEspecial;
    // End of variables declaration//GEN-END:variables
}
