/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Trabalho1;

/**
 *
 * @author Nicolau&Beatriz
 */
public class ConfirmacaoTransferencia extends javax.swing.JFrame {

    /**
     * Creates new form CadastroContaComum
     */
    public ConfirmacaoTransferencia() {
        initComponents();
    }
    
    int num1;
    int num2;
    double valorTransferir;
    String nomeTitular1 = new String();
    String nomeTitular2 =  new String();
    
    public void recebeValores(int numero1,int numero2, double valor, String origem, String destino) {
        num1 = numero1;
        num2 = numero2;
        valorTransferir = valor;
        String nomeTitular1 = origem; 
        String nomeTitular2 = destino; 
        // coloca o nome do titular da conta em Maisculo
        jLabelOrigem.setText(nomeTitular1.toUpperCase());
        jLabelDestino.setText(nomeTitular2.toUpperCase());
        mensagemSucesso.setVisible(false);
        voltaOperacoes.setVisible(false);
        
    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonTransferir = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        voltaOperacoes = new javax.swing.JButton();
        mensagemSucesso = new javax.swing.JLabel();
        jLabelOrigem = new javax.swing.JLabel();
        jLabelNumeroComum = new javax.swing.JLabel();
        jLabelDestino = new javax.swing.JLabel();
        jLabelD = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonTransferir.setText("TRANSFERIR");
        jButtonTransferir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTransferirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonTransferir);
        jButtonTransferir.setBounds(60, 140, 130, 30);

        jButtonCancelar.setText("CANCELAR");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar);
        jButtonCancelar.setBounds(210, 140, 130, 30);

        voltaOperacoes.setText("VOLTAR PARA OPERAÇÕES");
        voltaOperacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltaOperacoesActionPerformed(evt);
            }
        });
        getContentPane().add(voltaOperacoes);
        voltaOperacoes.setBounds(80, 170, 260, 30);

        mensagemSucesso.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        mensagemSucesso.setForeground(new java.awt.Color(255, 255, 255));
        mensagemSucesso.setText("OPERAÇÃO REALIZADA COM SUCESSO !");
        getContentPane().add(mensagemSucesso);
        mensagemSucesso.setBounds(70, 20, 340, 60);

        jLabelOrigem.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelOrigem.setForeground(new java.awt.Color(255, 255, 255));
        jLabelOrigem.setText("ORIGEM ");
        getContentPane().add(jLabelOrigem);
        jLabelOrigem.setBounds(160, 20, 130, 30);

        jLabelNumeroComum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNumeroComum.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumeroComum.setText("DESEJA TRANSFERIR PARA");
        getContentPane().add(jLabelNumeroComum);
        jLabelNumeroComum.setBounds(110, 50, 200, 30);

        jLabelDestino.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelDestino.setForeground(new java.awt.Color(255, 255, 255));
        jLabelDestino.setText("DESTINO");
        getContentPane().add(jLabelDestino);
        jLabelDestino.setBounds(160, 70, 110, 30);

        jLabelD.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelD.setForeground(new java.awt.Color(255, 255, 255));
        jLabelD.setText("?");
        getContentPane().add(jLabelD);
        jLabelD.setBounds(180, 90, 110, 30);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.jpg"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(0, 0, 412, 223);

        setSize(new java.awt.Dimension(429, 261));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    Principal transferir = new Principal();
    private void jButtonTransferirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTransferirActionPerformed
        
        jLabelOrigem.setVisible(false);
        jLabelNumeroComum.setVisible(false);
        jLabelDestino.setVisible(false);
        jButtonTransferir.setVisible(false);
        jButtonCancelar.setVisible(false);
        jLabelD.setVisible(false);        
        mensagemSucesso.setVisible(true);
        voltaOperacoes.setVisible(true);
        transferir.transferir(num1,num2,valorTransferir);
    }//GEN-LAST:event_jButtonTransferirActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        Operacoes voltaOperacoes = new Operacoes();
        voltaOperacoes.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void voltaOperacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltaOperacoesActionPerformed
       Operacoes voltaOperacoes = new Operacoes();
        voltaOperacoes.setVisible(true);
        dispose();
    }//GEN-LAST:event_voltaOperacoesActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroContaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroContaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroContaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroContaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroContaComum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonTransferir;
    private javax.swing.JLabel jLabelD;
    private javax.swing.JLabel jLabelDestino;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelNumeroComum;
    private javax.swing.JLabel jLabelOrigem;
    private javax.swing.JLabel mensagemSucesso;
    private javax.swing.JButton voltaOperacoes;
    // End of variables declaration//GEN-END:variables
}
