/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Trabalho1;

/**
 *
 * @author Nicolau&Beatriz
 */
public class ConfirmarDeposito extends javax.swing.JFrame {

    /**
     * Creates new form CadastroContaComum
     */
    public ConfirmarDeposito() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoCancelar = new javax.swing.JButton();
        botaoConfirmar = new javax.swing.JButton();
        jLabelTitular = new javax.swing.JLabel();
        jLabelMsgComplementar = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        botaoCancelar.setText("CANCELAR");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoCancelar);
        botaoCancelar.setBounds(240, 140, 130, 30);

        botaoConfirmar.setText("CONFIRMAR");
        botaoConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(botaoConfirmar);
        botaoConfirmar.setBounds(50, 140, 130, 30);

        jLabelTitular.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabelTitular.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(jLabelTitular);
        jLabelTitular.setBounds(170, 20, 180, 40);

        jLabelMsgComplementar.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabelMsgComplementar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMsgComplementar.setText("REALMENTE DESEJA REALIZAR O DEPÓSITO? ");
        getContentPane().add(jLabelMsgComplementar);
        jLabelMsgComplementar.setBounds(50, 70, 340, 30);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.jpg"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(0, 0, 412, 223);

        setSize(new java.awt.Dimension(429, 261));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    int numeroConta;
    double valorDeposito;
    String titular;
    
    Principal auxiliar = new Principal();
    //String titular = auxiliar.retornaTitular(numeroConta);
    
    public void recebeDados(int numero, double deposito, String titulaar){
        
        numeroConta = numero;
        valorDeposito = deposito;
        titular = titulaar;
        jLabelTitular.setText(titular.toUpperCase());
       
    }
    
    
    private void botaoConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoConfirmarActionPerformed
        Principal depositar = new Principal();
        depositar.depositar(numeroConta,valorDeposito);
        DepositoSucesso pTela = new DepositoSucesso();
        pTela.setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoConfirmarActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        Operacoes proximaTela = new Operacoes();
        proximaTela.setVisible(true);
        dispose();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    
   
    
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroContaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroContaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroContaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroContaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroContaComum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoConfirmar;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelMsgComplementar;
    private javax.swing.JLabel jLabelTitular;
    // End of variables declaration//GEN-END:variables
}
