/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Trabalho1;

/**
 *
 * @author Nicolau&Beatriz
 */
public class Confirmacao extends javax.swing.JFrame {

    /**
     * Creates new form CadastroContaComum
     */
    public Confirmacao() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCancelar = new javax.swing.JButton();
        jButtonConfirmar = new javax.swing.JButton();
        jLabelCorrentista = new javax.swing.JLabel();
        jLabelTextoComplementar = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonCancelar.setText("CANCELAR");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelar);
        jButtonCancelar.setBounds(220, 130, 130, 30);

        jButtonConfirmar.setText("CONFIRMAR");
        jButtonConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConfirmar);
        jButtonConfirmar.setBounds(40, 130, 130, 30);

        jLabelCorrentista.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabelCorrentista.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCorrentista.setText("CORRENTISTA");
        getContentPane().add(jLabelCorrentista);
        jLabelCorrentista.setBounds(150, 40, 180, 40);

        jLabelTextoComplementar.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabelTextoComplementar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTextoComplementar.setText("DESEJA REALMENTE REALIZAR A OPERAÇÃO ?");
        getContentPane().add(jLabelTextoComplementar);
        jLabelTextoComplementar.setBounds(50, 70, 330, 40);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.jpg"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(0, 0, 412, 223);

        setSize(new java.awt.Dimension(429, 261));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    // recebe os dados da tela anterior e armazena em variaveis
    int numeroConta;
    double valorSaque;
    String nomeTitular;
    
    public void recebeValores(int numero, double valor, String titular) {
        numeroConta = numero;
        valorSaque = valor;
        String nomeTitular = titular; 
        // coloca o nome do titular da conta em Maisculo
        jLabelCorrentista.setText(titular.toUpperCase());
    }
       
    Operacoes voltar = new Operacoes();
    Principal passarDados = new Principal();
    
    
    private void jButtonConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarActionPerformed
        Boolean possivelSacar = passarDados.sacar(numeroConta, valorSaque);
        
        if(possivelSacar){
             SacarSucesso proximaTela = new SacarSucesso();
             SacarSucessoEspecial proximaTelaEspecial = new SacarSucessoEspecial();
             if("cheque especial" == passarDados.tipoConta(numeroConta) && (valorSaque > passarDados.contaEspecial.get(0).getSaldo())){
                proximaTelaEspecial.setVisible(true);
                dispose();
             }else{
                proximaTela.setVisible(true);
                dispose();
             }
        }
        else{
            SacarInvalido proximaTela = new SacarInvalido();
            proximaTela.setVisible(true);
            dispose(); 
        }
    }//GEN-LAST:event_jButtonConfirmarActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        voltar.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroContaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroContaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroContaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroContaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroContaComum().setVisible(true);
            }
        });
    }
    // recebe os valores inserindo na tela anterior
    
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonConfirmar;
    private javax.swing.JLabel jLabelCorrentista;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelTextoComplementar;
    // End of variables declaration//GEN-END:variables
}
