/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Trabalho1;

import static java.lang.Double.parseDouble;
import static java.lang.Integer.parseInt;

/**
 *
 * @author Nicolau&Beatriz
 */
public class Deposito extends javax.swing.JFrame {

    /**
     * Creates new form CadastroContaComum
     */
    public Deposito() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonDepositar = new javax.swing.JButton();
        jLabelTituloComum = new javax.swing.JLabel();
        jTextNumero = new javax.swing.JTextField();
        jTextValorDeposito = new javax.swing.JTextField();
        jLabelNumeroComum = new javax.swing.JLabel();
        jLabelSaldoInicialComum = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonDepositar.setText("DEPOSITAR");
        jButtonDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDepositarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDepositar);
        jButtonDepositar.setBounds(200, 150, 130, 30);

        jLabelTituloComum.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabelTituloComum.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloComum.setText("DEPÓSITO");
        getContentPane().add(jLabelTituloComum);
        jLabelTituloComum.setBounds(150, 10, 120, 30);
        getContentPane().add(jTextNumero);
        jTextNumero.setBounds(160, 50, 200, 30);
        getContentPane().add(jTextValorDeposito);
        jTextValorDeposito.setBounds(160, 100, 200, 30);

        jLabelNumeroComum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNumeroComum.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumeroComum.setText("NÚMERO: ");
        getContentPane().add(jLabelNumeroComum);
        jLabelNumeroComum.setBounds(90, 50, 70, 30);

        jLabelSaldoInicialComum.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelSaldoInicialComum.setForeground(new java.awt.Color(255, 255, 255));
        jLabelSaldoInicialComum.setText("VALOR DE DEPÓSITO:");
        getContentPane().add(jLabelSaldoInicialComum);
        jLabelSaldoInicialComum.setBounds(10, 100, 150, 30);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.jpg"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(0, 0, 412, 223);

        setSize(new java.awt.Dimension(429, 261));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void jButtonDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDepositarActionPerformed
        Principal retornaTitular  = new Principal();
        ConfirmarDeposito dados = new ConfirmarDeposito();
        int numero = parseInt(jTextNumero.getText());
        double valor = parseDouble(jTextValorDeposito.getText());        
        String titular = retornaTitular.retornaTitular(numero);
        dados.recebeDados(numero,valor,titular);
        
        
        dados.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonDepositarActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroContaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroContaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroContaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroContaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroContaComum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonDepositar;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelNumeroComum;
    private javax.swing.JLabel jLabelSaldoInicialComum;
    private javax.swing.JLabel jLabelTituloComum;
    private javax.swing.JTextField jTextNumero;
    private javax.swing.JTextField jTextValorDeposito;
    // End of variables declaration//GEN-END:variables
}
