/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Trabalho1;

import static java.lang.Double.parseDouble;
import static java.lang.Integer.parseInt;

/**
 *
 * @author Nicolau&Beatriz
 */
public class Reajustar extends javax.swing.JFrame {

    /**
     * Creates new form CadastroContaComum
     */
    public Reajustar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonReajustar = new javax.swing.JButton();
        jLabelTituloComum = new javax.swing.JLabel();
        jTextNumeroReajuste = new javax.swing.JTextField();
        jTextTaxaReajuste = new javax.swing.JTextField();
        jLabelNumeroReajuste = new javax.swing.JLabel();
        jLabelTaxaReajuste = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonReajustar.setText("REAJUSTAR SALDO");
        jButtonReajustar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReajustarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonReajustar);
        jButtonReajustar.setBounds(150, 160, 180, 40);

        jLabelTituloComum.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabelTituloComum.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloComum.setText("REAJUSTAR CONTA POUPANÇA");
        getContentPane().add(jLabelTituloComum);
        jLabelTituloComum.setBounds(90, 20, 240, 30);
        getContentPane().add(jTextNumeroReajuste);
        jTextNumeroReajuste.setBounds(140, 60, 200, 30);
        getContentPane().add(jTextTaxaReajuste);
        jTextTaxaReajuste.setBounds(140, 110, 200, 30);

        jLabelNumeroReajuste.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelNumeroReajuste.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumeroReajuste.setText("NÚMERO: ");
        getContentPane().add(jLabelNumeroReajuste);
        jLabelNumeroReajuste.setBounds(70, 60, 70, 30);

        jLabelTaxaReajuste.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelTaxaReajuste.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTaxaReajuste.setText("TAXA DE REAJUSTE:");
        getContentPane().add(jLabelTaxaReajuste);
        jLabelTaxaReajuste.setBounds(10, 110, 160, 30);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.jpg"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(0, 0, 412, 223);

        setSize(new java.awt.Dimension(429, 261));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonReajustarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReajustarActionPerformed
        int numero = parseInt(jTextNumeroReajuste.getText());
        double taxa;        
        Principal reajustar = new Principal();
        if (jTextTaxaReajuste.getText().length() == 0){
            taxa = 0;
        }
        else{
            taxa = parseDouble(jTextTaxaReajuste.getText());
        }
        reajustar.reajustar(taxa,numero);
        ReajusteRealizado proximaTela = new ReajusteRealizado();
        proximaTela.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonReajustarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroContaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroContaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroContaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroContaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroContaComum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonReajustar;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelNumeroReajuste;
    private javax.swing.JLabel jLabelTaxaReajuste;
    private javax.swing.JLabel jLabelTituloComum;
    private javax.swing.JTextField jTextNumeroReajuste;
    private javax.swing.JTextField jTextTaxaReajuste;
    // End of variables declaration//GEN-END:variables
}
