/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Trabalho1;

import static java.lang.Double.parseDouble;
import static java.lang.Integer.parseInt;

/**
 *
 * @author Nicolau&Beatriz
 */
public class Sacar extends javax.swing.JFrame {

    /**
     * Creates new form CadastroContaComum
     */
    public Sacar() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSacar = new javax.swing.JButton();
        jLabelTituloSacar = new javax.swing.JLabel();
        jTextNumeroSacar = new javax.swing.JTextField();
        jTextValorSaque = new javax.swing.JTextField();
        jLabelInt1 = new javax.swing.JLabel();
        jLabeInd2 = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButtonSacar.setText("SACAR");
        jButtonSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSacarActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSacar);
        jButtonSacar.setBounds(130, 170, 130, 30);

        jLabelTituloSacar.setFont(new java.awt.Font("Leelawadee", 1, 14)); // NOI18N
        jLabelTituloSacar.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTituloSacar.setText("DIGITE OS DADOS PARA REALIZAR O SAQUE");
        getContentPane().add(jLabelTituloSacar);
        jLabelTituloSacar.setBounds(60, 30, 320, 20);
        getContentPane().add(jTextNumeroSacar);
        jTextNumeroSacar.setBounds(170, 60, 200, 30);
        getContentPane().add(jTextValorSaque);
        jTextValorSaque.setBounds(170, 110, 200, 30);

        jLabelInt1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelInt1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInt1.setText("NÚMERO DA CONTA: ");
        getContentPane().add(jLabelInt1);
        jLabelInt1.setBounds(30, 60, 140, 30);

        jLabeInd2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabeInd2.setForeground(new java.awt.Color(255, 255, 255));
        jLabeInd2.setText("VALOR PARA O SAQUE:");
        getContentPane().add(jLabeInd2);
        jLabeInd2.setBounds(20, 110, 160, 30);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo.jpg"))); // NOI18N
        getContentPane().add(jLabelFundo);
        jLabelFundo.setBounds(0, 0, 412, 223);

        setSize(new java.awt.Dimension(429, 261));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSacarActionPerformed
        Principal retornaTitular  = new Principal();
        Confirmacao dados = new Confirmacao();
        int numero = parseInt(jTextNumeroSacar.getText());
        double valor = parseDouble(jTextValorSaque.getText());        
        String titular = retornaTitular.retornaTitular(numero);
        dados.recebeValores(numero,valor,titular);
        
        dados.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButtonSacarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroContaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroContaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroContaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroContaComum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroContaComum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonSacar;
    private javax.swing.JLabel jLabeInd2;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JLabel jLabelInt1;
    private javax.swing.JLabel jLabelTituloSacar;
    private javax.swing.JTextField jTextNumeroSacar;
    private javax.swing.JTextField jTextValorSaque;
    // End of variables declaration//GEN-END:variables
}
